# specfile generated by rpmerizor (http://sourceforge.net/projects/rpmerizor/)

# if you are using __spec_only and want to build rpm package
# after, from command line, you have to use the following syntaxe
# rpmbuild -bb --buildroot=/tmp/rpmerizor_buildroot your_specfile.spec

# supported algorithm (cf rpmsign)
# may be SHA1, SHA256, SHA384, and SHA512
# represented as 2, 8, 9, and 10 respectively
# use 1 for md5 for compatibility with rpm < 4.6.0
# %global _binary_filedigest_algorithm 1
# %global _source_filedigest_algorithm 1

%define defaultbuildroot /
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0

%define name    torch-mlir
%define version 0.0.2

Summary: C and C++ PyTorch Interfaces to the MLIR Ecosystem.
Name: %{name}
Version: %{version}
Release: 500.fc41
License: Apache 2.0 With LLVM Exception
Group: Development Tools
BuildArch: x86_64
URL: https://github.com/llvm/torch-mlir
Packager: Stefan Teleman <stefan.teleman@ieee.org>
# autoreq and autoprov
AutoReqProv: yes

%description
The Torch-MLIR project aims to provide first class compiler support from the PyTorch ecosystem to the MLIR ecosystem.

%prep
ln -s /src/steleman/programming/torch-mlir/20251031/install-torch-mlir /tmp/rpmerizor_buildroot

%clean
rm /tmp/rpmerizor_buildroot

%files
%dir /opt/llvm/21.1.8
%dir /opt/llvm/21.1.8/bin
%dir /opt/llvm/21.1.8/include
%dir /opt/llvm/21.1.8/include/torch-mlir
%dir /opt/llvm/21.1.8/include/torch-mlir-c
%dir /opt/llvm/21.1.8/include/torch-mlir-dialects
%dir /opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect
%dir /opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor
%dir /opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR
%dir /opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/Transforms
%dir /opt/llvm/21.1.8/include/torch-mlir/Conversion
%dir /opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchConversionToMLProgram
%dir /opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchOnnxToTorch
%dir /opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToArith
%dir /opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToLinalg
%dir /opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToSCF
%dir /opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToStablehlo
%dir /opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToTMTensor
%dir /opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToTensor
%dir /opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToTosa
%dir /opt/llvm/21.1.8/include/torch-mlir/Conversion/Utils
%dir /opt/llvm/21.1.8/include/torch-mlir/Dialect
%dir /opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch
%dir /opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR
%dir /opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/Transforms
%dir /opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/Utils
%dir /opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion
%dir /opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/IR
%dir /opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/Transforms
%dir /opt/llvm/21.1.8/include/torch-mlir/RefBackend
%dir /opt/llvm/21.1.8/lib64
%dir /opt/llvm/21.1.8/lib64/objects-Release
%dir /opt/llvm/21.1.8/lib64/objects-Release/obj.TorchMLIRCAPI
%dir /opt/llvm/21.1.8/python_packages
%dir /opt/llvm/21.1.8/python_packages/torch_mlir
%dir /opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir
%dir /opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/_mlir_libs
%dir /opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/dialects
%dir /opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/dialects/torch
%dir /opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/extras
%dir /opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/tools
%dir /opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/tools/import_onnx
%dir /opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/tools/opt
%dir /opt/llvm/21.1.8/src
%dir /opt/llvm/21.1.8/src/python
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonExtensions.Main
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Dialects.torch
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Dialects.torch.ops_gen
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Dialects.torch.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Dialects.torch/dialects
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Dialects.torch/dialects/torch
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Importers
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Importers/extras
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.PublicAPI
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.PublicAPI/extras
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Tools
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Tools/tools
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Tools/tools/import_onnx
%dir /opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Tools/tools/opt
%dir /opt/llvm/21.1.8/src/python/TorchMLIRSiteInitialize
%dir /opt/llvm/21.1.8/src/python/TorchMLIRSiteInitialize/_mlir_libs
/opt/llvm/21.1.8/bin/mlir_builder_tblgen
/opt/llvm/21.1.8/bin/torch-mlir-capi-torch-test
/opt/llvm/21.1.8/bin/torch-mlir-import-onnx
/opt/llvm/21.1.8/bin/torch-mlir-lsp-server
/opt/llvm/21.1.8/bin/torch-mlir-opt
/opt/llvm/21.1.8/include/torch-mlir-c/Dialects.h
/opt/llvm/21.1.8/include/torch-mlir-c/Registration.h
/opt/llvm/21.1.8/include/torch-mlir-c/TorchOps.h
/opt/llvm/21.1.8/include/torch-mlir-c/TorchTypes.h
/opt/llvm/21.1.8/include/torch-mlir-c/Transforms.h
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR/ScalarLoopOpInterface.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR/ScalarLoopOpInterface.h.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorDialect.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorDialect.h.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorOpInterfaces.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorOpInterfaces.h.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorOps.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorOps.h.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorTypeInterfaces.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorTypeInterfaces.h.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorTypes.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorTypes.h.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/Transforms/Passes.capi.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/Transforms/Passes.capi.h.inc
/opt/llvm/21.1.8/include/torch-mlir-dialects/Dialect/TMTensor/Transforms/Passes.h.inc
/opt/llvm/21.1.8/include/torch-mlir/Conversion/Passes.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/Passes.h.inc
/opt/llvm/21.1.8/include/torch-mlir/Conversion/Passes.td
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchConversionToMLProgram/TorchConversionToMLProgram.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchOnnxToTorch/Passes.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchOnnxToTorch/Passes.h.inc
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchOnnxToTorch/Passes.td
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchOnnxToTorch/Patterns.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchOnnxToTorch/Utils.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToArith/TorchToArith.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToLinalg/TorchToLinalg.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToLinalg/Utils.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToSCF/TorchToSCF.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToStablehlo/StablehloLegalizeUtils.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToStablehlo/TorchToStablehlo.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToTMTensor/TorchToTMTensor.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToTensor/TorchToTensor.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToTosa/TorchToTosa.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeCommon.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h
/opt/llvm/21.1.8/include/torch-mlir/Conversion/Utils/Utils.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchBase.td
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchDialect.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchDialect.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchDialect.h.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchOps.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchOps.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchOps.h.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchOps.td
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchTraits.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchTypes.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchTypes.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchTypes.h.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/IR/TorchTypes.td
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/Transforms/Passes.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/Transforms/Passes.h.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/Transforms/Passes.td
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/Transforms/Transforms.capi.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/Transforms/Transforms.capi.h.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/Utils/SparsityUtils.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/Utils/TorchUpstream.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/Torch/Utils/Utils.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionBase.td
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionDialect.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionDialect.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionDialect.h.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionDialect.td
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionOps.cpp.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionOps.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionOps.h.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionOps.td
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/Transforms/BackendTypeConversion.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.h
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.h.inc
/opt/llvm/21.1.8/include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.td
/opt/llvm/21.1.8/include/torch-mlir/InitAll.h
/opt/llvm/21.1.8/include/torch-mlir/RefBackend/Passes.h
/opt/llvm/21.1.8/include/torch-mlir/RefBackend/Passes.h.inc
/opt/llvm/21.1.8/include/torch-mlir/RefBackend/Passes.td
/opt/llvm/21.1.8/lib64/libTorchMLIRCAPI.a
/opt/llvm/21.1.8/lib64/libTorchMLIRConversionPasses.a
/opt/llvm/21.1.8/lib64/libTorchMLIRConversionUtils.a
/opt/llvm/21.1.8/lib64/libTorchMLIRInitAll.a
/opt/llvm/21.1.8/lib64/libTorchMLIRRefBackend.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTMTensorDialect.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTMTensorPasses.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchConversionDialect.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchConversionPasses.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchConversionToMLProgram.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchDialect.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchOnnxToTorch.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchPasses.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchToArith.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchToLinalg.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchToSCF.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchToStablehlo.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchToTMTensor.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchToTensor.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchToTosa.a
/opt/llvm/21.1.8/lib64/libTorchMLIRTorchUtils.a
/opt/llvm/21.1.8/lib64/objects-Release/obj.TorchMLIRCAPI/Dialects.cpp.o
/opt/llvm/21.1.8/lib64/objects-Release/obj.TorchMLIRCAPI/Registration.cpp.o
/opt/llvm/21.1.8/lib64/objects-Release/obj.TorchMLIRCAPI/TorchOps.cpp.o
/opt/llvm/21.1.8/lib64/objects-Release/obj.TorchMLIRCAPI/TorchTypes.cpp.o
/opt/llvm/21.1.8/lib64/objects-Release/obj.TorchMLIRCAPI/Transforms.cpp.o
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/_mlir_libs/_site_initialize_0.py
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/_mlir_libs/_stablehlo.cpython-313-x86_64-linux-gnu.so
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/_mlir_libs/_torchMlir.cpython-313-x86_64-linux-gnu.so
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/_mlir_libs/libTorchMLIRAggregateCAPI.so
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/compiler_utils.py
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/dialects/_torch_ops_gen.py
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/dialects/torch/__init__.py
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/extras/fx_decomp_util.py
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/extras/fx_importer.py
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/extras/onnx_importer.py
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/fx.py
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/tools/import_onnx/__main__.py
/opt/llvm/21.1.8/python_packages/torch_mlir/torch_mlir/tools/opt/__main__.py
/opt/llvm/21.1.8/src/python/TorchMLIRPythonExtensions.Main/TorchMLIRModule.cpp
/opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Dialects.torch.ops_gen/dialects/_torch_ops_gen.py
/opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Dialects.torch/dialects/torch/__init__.py
/opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Importers/extras/fx_importer.py
/opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Importers/extras/onnx_importer.py
/opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.PublicAPI/compiler_utils.py
/opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.PublicAPI/extras/fx_decomp_util.py
/opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.PublicAPI/fx.py
/opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Tools/tools/import_onnx/__main__.py
/opt/llvm/21.1.8/src/python/TorchMLIRPythonSources.Tools/tools/opt/__main__.py
/opt/llvm/21.1.8/src/python/TorchMLIRSiteInitialize/_mlir_libs/_site_initialize_0.py

